### ISSUE TITLE
Issue related to logout

### ISSUE THREAD

**Issue by cparkhi** [pac4j/spring-webmvc-pac4j-boot-demo#1]
Hi, I tried using logout but it actually it isnt logging the user out in the demo app. Looks like because you are creating a new instance of WebContext and ProfileManager and calling logout on new instance only its not removing the profile info from the session. The profile manager is also creating new sessionStore. I could be wrong but I need the logout to work for my app and struggling for a while so thought of creating an issue.

**Comment by leleuj** [comment]
Very strange. I just ran the demo, logged in via Facebook and logged out and it worked. The `WebContext` is a wrapper around the current request and response. Do you have some specific configuration / tuning for session?
