### ISSUE TITLE
Using @EnableWebSecurity and Extending WebSecurityConfigurerAdapter Instead

### ISSUE THREAD

**Issue by tedwards-rogue** [pac4j/spring-webmvc-pac4j-boot-demo#2]
I would be interested to learn if any work was done to move this to extend WebSecurityConfigurerAdapter instead of WebMvcConfigurerAdapter and of course use the @EnableWebSecurity annotation. I may be wrong, but this seems to be the preferred direction for Spring Security at this time.

**Comment by leleuj** [comment]
`@EnableWebSecurity` is for Spring Security, but **pac4j is not Spring Security**, it's a Java security engine which various implementations (https://github.com/pac4j/pac4j):
- `spring-webmvc-pac4j` is a security library for Spring MVC based on pac4j and using interceptors: so you cannot use `@EnableWebSecurity` in this demo
- `spring-security-pac4j` is a pac4j implementation in the Spring Security world -> https://github.com/pac4j/spring-security-pac4j
