### ISSUE TITLE
Adding a HandlerInterceptor using WebSecurityConfigurerAdapter instead of WebMvcConfigurerAdapter

### ISSUE THREAD

**Issue by marioroman** [pac4j/spring-webmvc-pac4j-boot-demo#4]
Hi, I have the following configuration for my app:

```
@EnableTransactionManagement
@EnableWebSecurity
public class SecurityApiConfiguration
    extends WebSecurityConfigurerAdapter {
...
}
````
An I wanted to add an _HandlerInterceptorAdapter_.  Is that possible using _WebSecurityConfigurerAdapter_? I just see examples using _WebMvcConfigurerAdapter_.

Thanks!

**Comment by leleuj** [comment]
`spring-webmvc-pac4j` works on top of Spring MVC and you can therefore use the `WebMvcConfigurerAdapter`.

`WebSecurityConfigurerAdapter` comes from Spring Security, meaning you want to use Spring Security. In that case, you need to use `spring-security-pac4j` (and not `spring-webmvc-pac4j`).

`pac4j` is a powerful engine which runs on top of Spring MVC, Spring Security and many other frameworks.
