### ISSUE TITLE
How to do multitenant external auth

### ISSUE THREAD

**Issue by antonpiatek-imanage** [pac4j/spring-webmvc-pac4j-boot-demo#6]
I'm trying to integrate pac4j into a spring boot app with saml auth, but I need to be able to choose a different saml client for authentication based on an http header.
I can see how to create and register two saml clients into pac4j, but I've no idea how to get them into the spring security filter chains so that only the correct one is used.
I'm assuming I'd need to build a custom WebSecurityConfigurerAdapter with code to look at the header and then decide which saml client to use, but I can't see where to start with this.

Is there some documentation I'm failing to find, or examples anywhere which could help me?

**Comment by leleuj** [comment]
If two clients have been defined on the same protected URL, you can choose one or another using the `client_name` query parameter. Use the `setName` setter to define the name of the `SAML2Client`.

*Example:*

```java
registry.addInterceptor(new SecurityInterceptor(config, "saml1,saml2")).addPathPatterns("/protected*"));
```

Then, use the appropriate URL: `/protected?client_name=saml1` or `/protected?client_name=saml2`. 

Be cautious with the security concerns.
